### ISSUE TITLE
Handling Subversion branches 

### ISSUE THREAD

**Issue by rameshsr** [mrts/git-svn-bridge#3]
Thank you for sharing your thoughts and the scripts. The current model of the bridge and the scripts provided are mapping an svn branch to a corresponding git repository of its own. Is there any reason why a Git repository is needed for every svn branch? Why can't an svn branch be just a Git branch in the existing repository of the master branch  itself? Are there any known issues to map a svn branch to a corresponding Git branch and synchronize?

**Comment by mrts** [comment]
Hi @rameshsr! Yes, there are issues with mapping and synchronizing SVN branches to Git branches, it is hard to implement. If you need this, check out [SubGit](https://subgit.com/) that supports this out of the box.
